### ISSUE TITLE
关于您一篇博文的疑问

### ISSUE THREAD

**Issue by yuanlam** [rosjb/rosjb.github.io#2]
你好，在一个偶然的情况下，发现您的博文https://rosjb.github.io/2020/09/05/Options%E7%AE%80%E5%8D%95%E8%AE%BE%E7%BD%AE/ ，使用的是我写得一个笔记。这个笔记最早是我发在TG一个私密群的，我并不介意任何人做转发，但因为当初是发给群友看，没考虑做隐私保护，里面有的设备的MAC地址等私隐信息，能否请你把这部分信息做隐藏？
本来应该在您的博文底下回复的，无奈一直没法回复，所以才跑来这里开了一个issues，望见谅。

**Comment by T3rdW** [comment]
恩,MAC地址已做处理.如有任何问题可以发issues联系

**Comment by yuanlam** [comment]
非常感谢，您的其他博文也让我受益良多
